### ISSUE TITLE
Make the default configuration better/more consistent

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#12]
I'm still experimenting with the config (mostly message formatting in messages.yml). When I'm reasonably satisfied, I'll give the updated version to @RichardB122 so it can be in the actual build.

**Comment by fallerOfFalls** [comment]
Current messages.yml:

``` yaml
# Formatting Codes:
# listed below (for reference)
# ------------------------------
# BLACK: &0
# DARK_BLUE: &1
# DARK_GREEN: &2
# DARK_AQUA: &3
# DARK_RED: &4
# DARK_PURPLE: &5
# GOLD: &6
# GRAY: &7
# DARK_GRAY: &8
# BLUE: &9
# GREEN &a
# AQUA: &b
# RED: &c
# LIGHT_PURPLE: &d
# YELLOW: &e
# WHITE: &f
# MAGIC: &k
# BOLD: &l
# STRIKETHROUGH: &m
# UNDERLINE: &n
# ITALIC: &o
# RESET: &r
#
# Red status color is &4
# Green status color is &a
# Yellow status color is &6
#
# Status Color Codes
yellow: '&e'  
blue: '&9'
green: '&2' 
red: '&4'
#
# Messages
#
prefixBad: '&c'
prefixGood: '&6'
prefixMessage: '&6[PLAYER1&6->PLAYER2&6] &7'
errNoPerm: 'You do not have permission to use that command!'
yellowAdd: '{TARGET} added to yellow list.'
yellowDuplicate: '{TARGET} cannot be added because they are already on your yellow list.'
yellowRemove: '{TARGET} removed from yellow list'
yellowNoMatch: '{TARGET} cannot be removed because they are not on your yellow list.'
statusSetBlue: "You switched to &9Blue&6. This lets other players know you are a staff member."
statusSetYellow: 'You switched to &eYellow&6. Only {yellow_list} have permission to be in your party and message you.'
statusSetRed: 'You switched to &4Red&6. Players can neither message you nor join your party, and vice versa.'
statusSetWhite: 'You switched to &fWhite&6. Any player can message you or join your party.'
statusSetGreen: 'You switched to &2Green&6. Players are encouraged to message you or join your party.'
notValidPlayer: "Can't find {TARGET}! Either you mispelled their name, or they haven't logged in since AutismChat was installed."
globalChatOff: 'Global chat messages will not be displayed.'
globalChatOn: 'Global chat messages will be displayed.'
noAcceptingRed: '&5You cannot send {RECEIVER} messages because they are &4RED&c!'
noAcceptingYellow: '&5You cannot send {RECEIVER} messages because they are &6YELLOW&c and you are not on their list!'
noSendingRed: '&5You cannot send messages because you are &4RED&c!'
noSendingYellow: '&5You cannot send {RECEIVER} messages because you are &6YELLOW&c and they are not on your list!'
invalidArgs: 'Your command included invalid arguments. Usage:'
noMessageEntered: 'You must enter a message to send to global chat.'
nobodyHeardMessage: 'There are no other online players in your party so nobody heard your message. Consider joining another player in a party (/join ) or sending a message to global chat (/g )'
gcAutoEnabled: 'Global Chat has been automatically enabled so that you can see the response to your message.'
partyJoinErrorMessages:
    1: 'That player is red and you cannot join their party.'
    2: 'There are players in {MEMBERS}&c who are yellow and you are not on their yellow list.'
    3: 'You are &4RED&c and you cannot join a party while you are red.'
    4: 'You are yellow and there are players in that party who are not on your yellow list.'
    5: 'That player is already in your party.'
    6: 'The player you entered is you.' 
joinParty: '{PLAYER} &6has joined the party {MEMBERS}&6.'
leaveParty: '{PLAYER} &6has left the party {PLAYERS} {REASON}&6.'
leavingPartyWithOnlyOnePersonInIt: 'Since you are the only member in your party please consider joining another party directly. You cannot leave.'
loadingSettingsMsg: '&6Loading Settings...'
status:
  colourSetting: '&6Your colour status: {COLORSTATUS}'
  yellowList: '&6Your yellow list: &r{yellow_list}'
  globalChat: '&6Display global chat: &r{yesno}'
  partyMembers: '&6Players in party with you: &r{PARTYMEMBERS}&6 - of which &r{ONLINEPARTYMEMBERS}&6 are online.'
#
# Message of the day that is displayed to users when they first join
motd:
  - '&f-MESSAGE OF THE DAY-'
  - '&fThis server is running AutismChat 3.0. Source code is available at https://github.com/RichardsProjects/AutismChat3.'
  - '&fMessages typed into chat go to party chat, not global chat.'
  - '&fBASICS COMMANDS'
  - '&f/join &oplayername&f - you join &oplayername&f in a party.'
  - '&f/g &oyour message&f - sends &omessage&f to global chat (which players may or may not be listening to).'
  - '&f/leave - you leave the party and be on your own again.'
  - '&fFull guide at http://beeminecraftserver.weebly.com/autismchat.html'
#
# Chat formats for both party and global
partyChatFormat: "%name%&r:  &7%message%"
globalChatFormat: "&3[Global] %name%&r:  &7%message%"
```
