### ISSUE TITLE
"/yellow list" doesn't tell you who's yellow list you are in

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#13]
We can use the modular system from #6 to make this neat and configurable.
so, status in messages.yml will look like this:

``` yaml
loadingSettingsMsg: '&6Your current AutismChat settings are...'
status:
  colourSetting: 'Colour status: {COLORSTATUS}'
  YellowList: 'Yellow list: {yellow_list}'
  othersYellowList: 'You are on the yellow list(s) of {others_yellow_list}'
  globalChat: 'Display global chat: {yesno}'
  partyMembers: 'You are is a party with: {PARTYMEMBERS} of which {ONLINEPARTYMEMBERS} are online.'
```

and then add a line to config.yml:

``` yaml
status: 'globalChat,partyMembers'
loginReport: 'colourSetting,yellowList,othersYellowList,globalChat,partyMembers'
yellowListCommand: 'yellowList,othersYellowList'
```

Then the /yellow list command is a clone of /status; the only difference being that it checks yellowListCommand instead of status.

I'm calling it a bug because the "saying who's yellow list you are in" was clearly stated in the spec. But if doing it the way described above is significantly more work, then we can call it an enhancement.
