### ISSUE TITLE
Player names not 'AutismChat formatted'

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#17]
E.g. if the player is green, `{TARGET}` in

``` yaml
yellowAdd: '{TARGET} added to yellow list.'
yellowDuplicate: '{TARGET} cannot be added because they are already on your yellow list.'
yellowRemove: '{TARGET} removed from yellow list'
yellowNoMatch: '{TARGET} cannot be removed because they are not on your yellow list.'
```

should be green.

This issue also affects the output of `/yellow list`, but since #13 will replace `/yellow list` with a clone of `/status`, no point in fixing `/yellow list`.
