### ISSUE TITLE
Way to find out who's in your party

### ISSUE THREAD

**Issue by fallerOfFalls** [RichardsProjects/AutismChat3#6]
There's no way to check who's in your party without leaving and joining again. Is there any way to indicate in tablist which players are in your party?

A less ideal solution might be to add or modify a command.
E.g. make /join (with no arguments) tell you which party you're in.
Similarly /gc (with no arguments) can tell you whether global chat is switched on or not.

**Comment by Cassolotl** [comment]
I really want to be able to see who's in my party!

I think /join is really unintuitive. I do like /party though, and /status would be okay. If /status told me whether I could see global chat AND tell me who's in my party (online and offline, maybe the latter in grey) that'd be great.

**Comment by fallerOfFalls** [comment]
Good point. Okay, let's use /status and have it display both the list of party members and global chat setting.

**Comment by fallerOfFalls** [comment]
I'm unsure about exactly what /status should give us, so (you guessed it) let's make it configurable so that I can experiment.

In messages.yml there should be something like

``` yaml
loadingSettingsMsg: 'loading settings'
status:
  colourSetting: 'Your colour status: {COLORSTATUS}'
  yellowList: 'Your yellow list: {yellow_list}'
  globalChat: 'Display global chat: {yesno}'
  partyMembers: 'Players in party with you: {PARTYMEMBERS} of which {ONLINEPARTYMEMBERS} are online.'
```

Partymembers and onlinepartymembers should not include yourself. and if there are none it should say NONE. Or something.

Then config.yml should have something like

``` yaml
status: 'globalChat,partyMembers'
loginReport: 'colourSetting,yellowList,globalChat,partyMembers
```

Or however you make a list in yaml. The idea is to say which lines from messages.yml should be used by login report and /status, and to indicate the order in which they should be displayed. Does that make sense?
